import type { Cue, LayoutSettings, TranslationSettings, WorkspaceData } from "./types";

const cue = (
  cue_id: string,
  start_ms: number,
  end_ms: number,
  speaker_id: string,
  speaker_name: string,
  speaker_color: string,
  source_text: string,
  target_text: string,
  confidence: number,
  layer = 0,
  group_id: string | null = null,
): Cue => ({
  cue_id,
  start_ms,
  end_ms,
  group_id,
  overlap_group_id: group_id,
  layer,
  track: layer,
  speaker_id,
  speaker_name,
  speaker_color,
  source_kind: "ocr",
  source_text,
  ocr_confidence: confidence,
  target_text,
  review_status: confidence < 0.9 ? "needs_review" : target_text ? "approved" : "pending",
  bbox: {
    x: layer === 0 ? 0.18 : 0.52,
    y: layer === 0 ? 0.77 : 0.69,
    width: layer === 0 ? 0.64 : 0.37,
    height: 0.08,
  },
  warnings: confidence < 0.9 ? ["low_ocr_confidence"] : [],
});

export const demoCues: Cue[] = [
  cue("000001", 1200, 3900, "SPK_01", "Mira", "#f0c75e", "The train leaves before sunrise.", "列车会在日出前出发。", 0.987),
  cue("000002", 4300, 6800, "SPK_02", "Ren", "#66c7b5", "Then we should not waste another minute.", "那我们一分钟也别浪费。", 0.962),
  cue("000003", 7200, 10100, "SPK_01", "Mira", "#f0c75e", "Did you bring the archive key?", "档案库的钥匙带了吗？", 0.934),
  cue("000004", 10200, 12800, "SPK_02", "Ren", "#66c7b5", "I thought you had it.", "我以为在你那里。", 0.888),
  cue("000005", 13400, 16400, "SPK_01", "Mira", "#f0c75e", "Wait. Someone is coming.", "等等，有人来了。", 0.975),
  cue("000006", 17000, 19800, "SPK_03", "Guard", "#d58b72", "Stop right there!", "站住！", 0.941, 0, "OV-01"),
  cue("000007", 17150, 20500, "SPK_02", "Ren", "#66c7b5", "Run, Mira!", "快跑，米拉！", 0.954, 1, "OV-01"),
  cue("000008", 21400, 24800, "SPK_01", "Mira", "#f0c75e", "The west gate is still open.", "西门还开着。", 0.903),
  cue("000009", 25400, 29300, "SPK_02", "Ren", "#66c7b5", "Not for long.", "撑不了多久。", 0.861),
  cue("000010", 30700, 34800, "SPK_01", "Mira", "#f0c75e", "Meet me beyond the river.", "到河对岸找我。", 0.984),
  cue("000011", 35600, 38900, "SPK_02", "Ren", "#66c7b5", "You had better be there.", "你最好说到做到。", 0.972),
  cue("000012", 40300, 45200, "SPK_03", "Guard", "#d58b72", "Seal every exit!", "封锁所有出口！", 0.915),
];

export const defaultTranslationSettings: TranslationSettings = {
  base_url: "https://relay.example.com/v1",
  api_key: "",
  model: "gpt-4.1-mini",
  reasoning_effort: "",
  path: "/chat/completions",
  custom_headers: "{}",
  timeout_seconds: 90,
  concurrency: 2,
  send_title: true,
  send_story_context: true,
  send_character_profiles: true,
  send_glossary: true,
};

export const defaultLayoutSettings: LayoutSettings = {
  font_family: "Noto Sans SC",
  font_size: 42,
  outline: 3,
  max_lines: 2,
  max_chars: 22,
  color_mode: "speaker",
  avoid_faces: true,
  avoid_source: true,
  overlap_mode: "layers",
};

export const demoWorkspace: WorkspaceData = {
  project: {
    id: "demo-project",
    title: "The Last Archive",
    video_name: "the-last-archive-ep01.mkv",
    video_url: null,
    duration_ms: 58000,
    width: 1920,
    height: 1080,
    fps: 23.976,
    source_language: "English",
    target_language: "简体中文",
    source_roi: { x: 0.12, y: 0.68, width: 0.76, height: 0.22 },
    target_roi: { x: 0.12, y: 0.08, width: 0.76, height: 0.17 },
    context: {
      synopsis: "Two archivists race to recover a lost key before the city gates close.",
      characters: "Mira: decisive archivist. Ren: cautious partner. Guard: city patrol.",
      glossary: "archive key=档案库钥匙; west gate=西门",
      translation_style: "Natural cinematic dialogue, concise, preserve urgency.",
    },
  },
  cues: demoCues,
  jobs: [
    {
      id: "job-ocr-demo",
      kind: "ocr",
      status: "completed",
      stage: "multi_frame_verification",
      progress: 1,
      message: "12 cues extracted; 3 need review",
    },
    {
      id: "job-translate-demo",
      kind: "translation",
      status: "running",
      stage: "contextual_translation",
      progress: 0.68,
      message: "Translating batch 3 of 4",
    },
  ],
  translation_settings: defaultTranslationSettings,
  layout_settings: defaultLayoutSettings,
};
